 <?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Jose\Deviget\Block\Widget\Social\Block */

?>

 <section id="social-networks-widget">
     <h1><?= __('social_follow') ?></h1>

     <section id="social-icons">
         <div class="icon icon-twitter">
             <a href="#"><img src="<?= $this->getViewFileUrl('Jose_Deviget::images/transparency.png') ?>" /></a>
         </div>

         <div class="icon icon-facebook">
             <a href="#"><img src="<?= $this->getViewFileUrl('Jose_Deviget::images/transparency.png') ?>" /></a>
         </div>

         <div class="icon icon-pinterest">
             <a href="#"><img src="<?= $this->getViewFileUrl('Jose_Deviget::images/transparency.png') ?>" /></a>
         </div>

         <div class="icon icon-googleplus">
             <a href="#"><img src="<?= $this->getViewFileUrl('Jose_Deviget::images/transparency.png') ?>" /></a>
         </div>

         <div class="icon icon-rss">
             <a href="#"><img src="<?= $this->getViewFileUrl('Jose_Deviget::images/transparency.png') ?>" /></a>
         </div>
     </section>
 </section>