<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var $block \Jose\Deviget\Block\Cms\Entries */
?>

<div class="entry">
    <h1><?= __('cms-entry_title') ?></h1>
    <small><?= sprintf(__('by <p>%s</p> on %s'), 'Syed Balkhi', 'August 6, 2013') ?></small>

    <div class="content">
        <div class="image">
            <div class="placeholder-text">
                <span><?= __('entry_placeholder_image') ?></span>
            </div>
        </div>
        <p class="text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec magna venenatis, molestie nisi sed, placerat sapien. Nunc pulvinar dignissim sem eu viverra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. In eget dui eu leo ullamcorper faucibus vitae eu magna. Donec sed elementum enim.
        </p>
    </div>

    <div class="options">
        <div class="categories"><?= sprintf(__('Categories <p>%s</p>'), 'Business, Marketing') ?></div>
        <div class="continue"><?= __('continue_reading') ?></div>
    </div>
</div>
